### ISSUE TITLE
Roadmap to Expecta 1.0

### ISSUE THREAD

**Issue by orta** [specta/expecta#127]
This is a corollary issue to [Specta 1.0 Roadmap](https://github.com/specta/specta/issues/125)

The idea being that Expecta should get ready for the future and continue to be a rockin' Objective-C matcher library. Given the large amounts of `#define` macros in the library it's worth focusing on getting something stable for what we have now.

Things that should get done:

 - [x] `  #define EXP_SHORTHAND` cannot be done in a framework, switch EXP_ to not be default https://github.com/specta/expecta/issues/124 
 - [x] Come up with a nice way to explicitly fail a test https://github.com/specta/expecta/issues/96
 - [x] Close this question: https://github.com/specta/expecta/issues/121 
 - [x] close - https://github.com/specta/expecta/issues/25 ( https://github.com/specta/expecta/issues/87 has the fix )
 - [x] Close a bunch of issues that are "here's a matcher" saying that it's easy to make a Pod / Lib for this, if the use case is only useful for a subset of people.
 - [x] Rename notifiy https://github.com/specta/expecta/pull/114
 - [x] Merge this regex matcher https://github.com/specta/expecta/pull/105/files
 - [x] Merge theis PR about the deallocing the actual block  https://github.com/specta/expecta/pull/126
 - [x] Fix the decimal / number bug - https://github.com/specta/expecta/pull/119/files

**Comment by orta** [comment]
OK, that's all my things done. Will give this a bit of time to settle, then 1.0.0 them both in early May.

**Comment by robb** [comment]
Amazing work, :+1:
